### ISSUE TITLE
Autocomplete not consistent

### ISSUE THREAD

**Issue by cmeyertons** [cyrilletuzi/vscode-typescript-angular-plugin#5] opened 2018-11-19 15:36 UTC
Autocomplete does not consistently work inside HTML.  This is not a problem with the old extension and therefore is a problem with this extension, not the underlying language service

Event bindings look okay.

![image](https://user-images.githubusercontent.com/19917677/48717099-54a27480-ebde-11e8-8df4-376e8f159ff4.png)

Attribute bindings do not:

![image](https://user-images.githubusercontent.com/19917677/48717122-671cae00-ebde-11e8-8f62-241aa3e5db8f.png)

*ngIf does not:

![image](https://user-images.githubusercontent.com/19917677/48717203-87e50380-ebde-11e8-9b9f-a6b6bddf1a6f.png)

**Comment by cyrilletuzi** [comment] 2018-11-19 15:50
@cmeyertons Can't reproduce this issue.

Important questions:
- is the legacy extension disabled?
- what is the version of Angular in your project?

**Comment by cyrilletuzi** [comment] 2018-11-27 18:02
Closing for house keeping purpose, as no reproduction has been provided. Feel free to add more information and I'll re-open the issue.

**Closed by cyrilletuzi** 2018-11-27 18:02 UTC
Labels: needs repro
